export type Event = {time:number; type:string; message:string; seq?:number; worker_id?:string};
export type Agent = {
  id:string; name:string; provider:'codex'|'claude'; state:string; source:string; cwd:string;
  pid:number|null; created:number; cpu:number|null; memory:number|null; children?:number; note?:string;
  controls:string[]; protected:boolean; session_id?:string; access?:string; exit_code?:number;
  logs?:{time:number;text:string}[]; log_truncated?:boolean;
  open_files?:{path:string;pid:number;kind:string}[]; process_tree?:{pid:number;name:string;status:string}[]; inspection_error?:string;
};
export type Worker = {id:string;name:string;kind:string;state:string;attempt:string;progress:number;total:number;waiting:string|null;needs:string[];checkpoint_work:number;checkpoint_id:string|null;last_progress:number;capabilities:string[]};
export type Resource = {id:string;name:string;owner:string|null;version:number;capacity:number;exclusive:boolean};
export type Candidate = {id:string;worker_id:string;operation:string;lost_work:number;checkpoint_work:number;evidence_id:string;snapshot_id:string};
export type Incident = {id:string;status:string;key:string;members:string[];resources:string[];detected:number;ended:number|null;attempts:number;tool_calls:number;model:string|null;reason:string|null;
  trace:{time:number;tool:string;arguments:unknown;result:unknown}[];
  plan:{id:string;rationale:string;candidate:Candidate}|null;
  verification:{valid:boolean;resources_clear:boolean;evidence_complete:boolean;checks:{worker_id:string;completed:boolean;valid:boolean;error?:string}[]}|null;
};
export type Run = {id:string;scenario:string;strategy:string;status:string;seed:number;started:number;ended:number|null;auto_recover:boolean;mode:string;workers:Worker[];resources:Resource[];incident:Incident|null;events:Event[];evidence_gap:boolean;discarded_work:number;preserved_work:number;artifacts:{worker_id:string;filename:string;valid:boolean;size:number;sha256:string}[]};
export type State = {time:number;agents:Agent[];run:Run|null;host:{cpu:number;memory_used:number;memory_total:number;logical_cpus:number;platform:string;updated:number};
  telemetry:{engine:string;available:boolean;error:string|null;last_success:number|null};
  integrations:{codex:boolean;claude:boolean;codex_sessions:string|null;mediator:string};roots:string[];scenarios:Record<string,string>;events:Event[];errors:{component:string;error:string}[];
};
